import time
from selenium import webdriver

driver = webdriver.Chrome()
driver.get('http://localhost:8080/')
username = driver.find_element_by_name('username')
username.clear()
username.send_keys('admin')
password = driver.find_element_by_name('password')
password.clear()
password.send_keys('123456')
driver.find_element_by_css_selector("button.btn.btn-default").click()

time.sleep(1)

driver.find_element_by_xpath("//ul[@id='accordion']/li[3]/div").click()
time.sleep(1)
driver.find_element_by_link_text(u"项目报价").click()
driver.find_element_by_name("contractAmount").clear()
driver.find_element_by_name("contractAmount").send_keys("100000")
driver.find_element_by_name("nper").clear()
driver.find_element_by_name("nper").send_keys("12")
driver.find_element_by_name("leavePrice").clear()
driver.find_element_by_name("leavePrice").send_keys("0")
driver.find_element_by_name("rebateFee").clear()
driver.find_element_by_name("rebateFee").send_keys("0")
driver.find_element_by_name("yearRate").clear()
driver.find_element_by_name("yearRate").send_keys("0.12")
driver.find_element_by_name("firstRate").clear()
driver.find_element_by_name("firstRate").send_keys("0.3")
driver.find_element_by_name("marginRate").clear()
driver.find_element_by_name("marginRate").send_keys("0.1")
driver.find_element_by_name("manageRate").clear()
driver.find_element_by_name("manageRate").send_keys("0.01")
driver.find_element_by_name("consultRate").clear()
driver.find_element_by_name("consultRate").send_keys("0")
# driver.find_element_by_id("searchBtn").click()
driver.find_element_by_id("exportBtn").click()
